const repo = require("./targets.repository");

// ==========================================
// BUSINESS TARGETS SERVICE
// ==========================================

exports.getBusinessTarget = async (year, month) => {
  const { data, error } = await repo.getBusinessTarget(year, month);

  if (error && error.code !== "PGRST116") {
    // PGRST116 = no rows returned
    throw new Error("FAILED_TO_FETCH_BUSINESS_TARGET");
  }

  // If no target found, calculate fallback
  if (!data) {
    const fallbackTarget = await calculateFallbackTarget(year, month);
    return {
      ...fallbackTarget,
      isAutoGenerated: true,
    };
  }

  return data;
};

exports.getYearlyBusinessTargets = async (year) => {
  const { data, error } = await repo.getYearlyBusinessTargets(year);

  if (error) throw new Error("FAILED_TO_FETCH_YEARLY_TARGETS");

  // Fill in missing months with fallbacks
  const targetsMap = new Map(data?.map((t) => [t.month, t]) || []);
  const completeTargets = [];

  for (let month = 1; month <= 12; month++) {
    if (targetsMap.has(month)) {
      completeTargets.push(targetsMap.get(month));
    } else {
      const fallback = await calculateFallbackTarget(year, month);
      completeTargets.push({
        ...fallback,
        isAutoGenerated: true,
        isPlaceholder: true,
      });
    }
  }

  return completeTargets;
};

exports.saveBusinessTarget = async (targetData, userId) => {
  const { year, month, ...data } = targetData;

  if (!year || !month) {
    throw new Error("YEAR_AND_MONTH_REQUIRED");
  }

  const sanitized = sanitizeNumeric(data, [
    "target_revenue",
    "target_gross_margin",
    "target_cash_reserve_days",
    "max_outstanding_ratio",
    "default_staff_target_revenue",
    "target_avg_bill_value",
    "target_bill_count",
    "target_inventory_turnover",
  ]);

  const payload = {
    year,
    month,
    ...sanitized,
    updated_by: userId,
  };

  // Check if target exists
  const { data: existing } = await repo.getBusinessTarget(year, month);

  if (existing) {
    // Update
    const { data: updated, error } = await repo.updateBusinessTarget(
      existing.id,
      payload,
    );
    if (error) throw new Error("FAILED_TO_UPDATE_BUSINESS_TARGET");
    return updated;
  } else {
    // Insert
    payload.created_by = userId;
    const { data: created, error } = await repo.upsertBusinessTarget(payload);
    if (error) throw new Error("FAILED_TO_CREATE_BUSINESS_TARGET");
    return created;
  }
};

exports.bulkUpdateBusinessTargets = async (year, targets, userId) => {
  if (!Array.isArray(targets)) {
    throw new Error("INVALID_TARGETS_ARRAY");
  }

  const results = [];

  for (const target of targets) {
    const saved = await exports.saveBusinessTarget({ ...target, year }, userId);
    results.push(saved);
  }

  return results;
};

// ==========================================
// USER/STAFF TARGETS SERVICE
// ==========================================

exports.getUserTarget = async (userId, year, month) => {
  const { data, error } = await repo.getUserTarget(userId, year, month);

  if (error && error.code !== "PGRST116") {
    throw new Error("FAILED_TO_FETCH_USER_TARGET");
  }

  if (!data) {
    // Return default target
    return {
      user_id: userId,
      year,
      month,
      target_revenue: 50000,
      target_bill_count: null,
      target_avg_bill_value: null,
      isDefault: true,
    };
  }

  return data;
};

exports.getAllUserTargets = async (year, month) => {
  const { data, error } = await repo.getAllUserTargets(year, month);

  if (error) {
    console.log("Error fetching users targets:", error);
    throw new Error("FAILED_TO_FETCH_USER_TARGETS");
  }

  return data || [];
};

exports.saveUserTarget = async (targetData, userId) => {
  const { user_id, year, month, ...data } = targetData;

  if (!user_id || !year || !month) {
    throw new Error("USER_YEAR_MONTH_REQUIRED");
  }

  const sanitized = sanitizeNumeric(data, [
    "target_revenue",
    "target_bill_count",
    "target_avg_bill_value",
  ]);

  const payload = {
    user_id,
    year,
    month,
    ...sanitized,
    updated_by: userId,
    created_by: userId,
  };

  const { data: saved, error } = await repo.upsertUserTarget(payload);

  if (error) {
    throw new Error("FAILED_TO_SAVE_USER_TARGET");
  }

  return saved;
};

exports.bulkUpdateUserTargets = async (year, month, targets, userId) => {
  if (!Array.isArray(targets)) {
    throw new Error("INVALID_TARGETS_ARRAY");
  }

  const results = [];

  for (const target of targets) {
    const saved = await exports.saveUserTarget(
      { ...target, year, month },
      userId,
    );
    results.push(saved);
  }

  return results;
};

// ==========================================
// CATEGORY TARGETS SERVICE
// ==========================================

exports.getCategoryTargets = async (year, month) => {
  const { data, error } = await repo.getCategoryTargets(year, month);

  if (error) throw new Error("FAILED_TO_FETCH_CATEGORY_TARGETS");

  return data || [];
};

exports.saveCategoryTarget = async (targetData, userId) => {
  const { category_id, year, month, ...data } = targetData;

  if (!category_id || !year || !month) {
    throw new Error("CATEGORY_YEAR_MONTH_REQUIRED");
  }

  const sanitized = sanitizeNumeric(data, ["target_revenue"]);

  const payload = {
    category_id,
    year,
    month,
    ...sanitized,
    updated_by: userId,
    created_by: userId,
  };

  const { data: saved, error } = await repo.upsertCategoryTarget(payload);

  if (error) throw new Error("FAILED_TO_SAVE_CATEGORY_TARGET");

  return saved;
};

// ==========================================
// DASHBOARD INTEGRATION
// ==========================================

exports.getDashboardTargets = async (year, month, currentMetrics = {}) => {
  // Get business target
  const businessTarget = await exports.getBusinessTarget(year, month);

  // Get user targets
  const userTargets = await exports.getAllUserTargets(year, month);

  // Build staff targets map
  const staffTargetsMap = {};
  for (const target of userTargets) {
    staffTargetsMap[target.user_id] = target;
  }

  // Calculate gaps
  const actualRevenue = currentMetrics.totalRevenue || 0;
  const targetRevenue = businessTarget.target_revenue || 0;
  const revenueGap = Math.max(0, targetRevenue - actualRevenue);

  const actualMargin = currentMetrics.grossMargin || 0;
  const targetMargin = businessTarget.target_gross_margin || 35;
  const marginGap = targetMargin - actualMargin;

  return {
    // Main targets
    targetRevenue,
    targetGrossMargin: targetMargin,
    targetCashReserveDays: businessTarget.target_cash_reserve_days || 30,
    targetOutstandingRatio: businessTarget.max_outstanding_ratio || 20,

    // Staff defaults
    defaultStaffTargetRevenue:
      businessTarget.default_staff_target_revenue || 50000,

    // Staff-specific targets
    staffTargetsMap,

    // Metadata
    isAutoGenerated: businessTarget.isAutoGenerated,

    // Calculated gaps
    revenueGap,
    marginGap,
  };
};

// ==========================================
// HELPER FUNCTIONS
// ==========================================

/**
 * Converts empty strings to null for numeric fields so the DB
 * doesn't receive invalid input (e.g. "" for a numeric column).
 */
function sanitizeNumeric(obj, fields) {
  const out = { ...obj };
  for (const field of fields) {
    if (out[field] === "" || out[field] === undefined) {
      out[field] = null;
    } else if (out[field] !== null) {
      out[field] = Number(out[field]) || null;
    }
  }
  return out;
}

async function calculateFallbackTarget(year, month) {
  // Calculate previous month
  let prevYear = year;
  let prevMonth = month - 1;
  if (prevMonth === 0) {
    prevMonth = 12;
    prevYear = year - 1;
  }

  // Get previous month's actual revenue
  const prevRevenue = await repo.getPreviousMonthRevenue(year, month);

  // Apply 10% growth
  const targetRevenue =
    prevRevenue > 0 ? Math.round(prevRevenue * 1.1) : 1000000;

  return {
    year,
    month,
    target_revenue: targetRevenue,
    target_gross_margin: 35,
    target_cash_reserve_days: 30,
    max_outstanding_ratio: 20,
    default_staff_target_revenue: Math.round(targetRevenue / 20), // Estimate: 20 staff
    target_avg_bill_value: null,
    target_bill_count: null,
    target_inventory_turnover: 4,
  };
}
