import api from "@/api";
import { getDashboardTargets } from "./targets.service";

// ==========================================
// MAIN DASHBOARD METRICS (WITH TARGETS)
// ==========================================

export const fetchDashboardMetrics = async (startDate, endDate) => {
  // Fetch core metrics from backend
  const { data: metricsResponse } = await api.get("/reports/dashboard", {
    params: { startDate, endDate },
  });
  
  const coreMetrics = metricsResponse.data || {};
  
  // Extract year/month from dates for target lookup
  const dateObj = new Date(startDate);
  const year = dateObj.getFullYear();
  const month = dateObj.getMonth() + 1; // 1-12
  
  // Enrich with targets (auto-fallback to last month + 10% if not set)
  let targets = {};
  try {
    targets = await getDashboardTargets(year, month, {
      totalRevenue: coreMetrics.totalRevenue,
      previousRevenue: coreMetrics.previousRevenue,
      grossMargin: coreMetrics.grossMargin || 
        (coreMetrics.totalRevenue ? ((coreMetrics.totalRevenue - (coreMetrics.cogs || 0)) / coreMetrics.totalRevenue) * 100 : 35),
    });
  } catch (e) {
    console.warn("Failed to fetch targets, using defaults:", e);
    // Fallback defaults
    targets = {
      targetRevenue: (coreMetrics.previousRevenue || coreMetrics.totalRevenue || 100000) * 1.10,
      targetGrossMargin: 35,
      targetCashReserveDays: 30,
      defaultStaffTargetRevenue: 50000,
      staffTargetsMap: {},
      isAutoGenerated: true,
    };
  }
  
  // Apply staff targets to staff performance data
  const enrichedStaffPerformance = (coreMetrics.staffPerformance || []).map(staff => {
    const staffTarget = targets.staffTargetsMap[staff.user_id] || {};
    return {
      ...staff,
      target_revenue: staffTarget.target_revenue || targets.defaultStaffTargetRevenue || 50000,
      target_bill_count: staffTarget.target_bill_count || null,
      target_avg_bill_value: staffTarget.target_avg_bill_value || null,
    };
  });
  
  // Combine everything
  return {
    ...coreMetrics,
    
    // Targets
    targetRevenue: targets.targetRevenue,
    targetGrossMargin: targets.targetGrossMargin,
    targetCashReserveDays: targets.targetCashReserveDays,
    targetOutstandingRatio: targets.targetOutstandingRatio,
    
    // Gap calculations for dashboard
    revenueGap: targets.revenueGap,
    marginGap: targets.marginGap,
    
    // Metadata
    targetsAutoGenerated: targets.isAutoGenerated,
    targetsUnsaved: targets.isUnsaved,
    
    // Enriched staff data
    staffPerformance: enrichedStaffPerformance,
  };
};

// ==========================================
// OTHER REPORTS (unchanged)
// ==========================================

export const fetchPerformanceComparisons = async (startDate, endDate) => {
  const { data } = await api.get("/reports/performance-comparisons", {
    params: { startDate, endDate },
  });
  return data.data;
};

export const fetchBalanceSheet = async (asOfDate) => {
  const { data } = await api.get("/reports/balance-sheet", {
    params: { asOfDate },
  });
  return data.data;
};

export const fetchIncomeStatement = async (startDate, endDate) => {
  const { data } = await api.get("/reports/income-statement", {
    params: { startDate, endDate },
  });
  return data.data;
};

export const fetchTrialBalance = async (startDate, endDate) => {
  const { data } = await api.get("/reports/trial-balance", {
    params: { startDate, endDate },
  });
  return data.data;
};

export const fetchCashFlowStatement = async (startDate, endDate) => {
  const { data } = await api.get("/reports/cash-flow", {
    params: { startDate, endDate },
  });
  return data.data;
};

export const fetchEquityChanges = async (startDate, endDate) => {
  const { data } = await api.get("/reports/equity-changes", {
    params: { startDate, endDate },
  });
  return data.data;
};

export const fetchZReport = async (date) => {
  const { data } = await api.get("/reports/z-report", {
    params: { date },
  });
  return data.data;
};
