import api from "@/api";

// ==========================================
// BUSINESS TARGETS API
// ==========================================

/**
 * Get business targets for a specific month
 * Falls back to previous month + 10% if no target set
 */
export const fetchBusinessTarget = async (year, month) => {
  try {
    const { data } = await api.get(`/targets/business/${year}/${month}`);
    return data.data;
  } catch (error) {
    // If no target found, calculate fallback
    if (error.response?.status === 404) {
      return calculateFallbackTarget(year, month);
    }
    throw error;
  }
};

/**
 * Get or create business target with fallback logic
 */
export const getOrCreateBusinessTarget = async (year, month, fallbackRevenue = null) => {
  try {
    const { data } = await api.get(`/targets/business/${year}/${month}`);
    return data.data;
  } catch (error) {
    if (error.response?.status === 404) {
      // Calculate fallback: last month actual + 10%
      const fallback = await calculateFallbackTarget(year, month, fallbackRevenue);
      
      // Auto-create target with fallback values
      try {
        const { data } = await api.post('/targets/business', {
          year,
          month,
          target_revenue: fallback.target_revenue,
          target_gross_margin: fallback.target_gross_margin || 35,
          target_cash_reserve_days: fallback.target_cash_reserve_days || 30,
          default_staff_target_revenue: fallback.default_staff_target_revenue || 50000,
          auto_generated: true
        });
        return { ...data.data, isAutoGenerated: true };
      } catch (createError) {
        // If creation fails, return fallback without saving
        return { ...fallback, isAutoGenerated: true, isUnsaved: true };
      }
    }
    throw error;
  }
};

/**
 * Create or update business target
 */
export const saveBusinessTarget = async (targetData) => {
  const { year, month, ...data } = targetData;
  const { data: response } = await api.post('/targets/business', {
    year,
    month,
    ...data,
    auto_generated: false
  });
  return response.data;
};

/**
 * Update existing business target
 */
export const updateBusinessTarget = async (id, updates) => {
  const { data } = await api.patch(`/targets/business/${id}`, updates);
  return data.data;
};

/**
 * Get all targets for a year (for settings page)
 */
export const fetchYearlyTargets = async (year) => {
  const { data } = await api.get(`/targets/business/year/${year}`);
  return data.data;
};

/**
 * Bulk update targets for a year
 */
export const bulkUpdateTargets = async (year, targets) => {
  const { data } = await api.post(`/targets/business/bulk/${year}`, { targets });
  return data.data;
};

// ==========================================
// USER/STAFF TARGETS API
// ==========================================

/**
 * Get user target for a specific month
 */
export const fetchUserTarget = async (userId, year, month) => {
  try {
    const { data } = await api.get(`/targets/user/${userId}/${year}/${month}`);
    return data.data;
  } catch (error) {
    if (error.response?.status === 404) {
      // Return default target
      return {
        user_id: userId,
        year,
        month,
        target_revenue: 50000,
        target_bill_count: null,
        target_avg_bill_value: null,
        isDefault: true
      };
    }
    throw error;
  }
};

/**
 * Save user target
 */
export const saveUserTarget = async (targetData) => {
  const { data } = await api.post('/targets/user', targetData);
  return data.data;
};

/**
 * Get all staff targets for a month
 */
export const fetchAllUserTargets = async (year, month) => {
  const { data } = await api.get(`/targets/users/${year}/${month}`);
  return data.data;
};

/**
 * Bulk update staff targets
 */
export const bulkUpdateUserTargets = async (year, month, targets) => {
  const { data } = await api.post(`/targets/users/bulk/${year}/${month}`, { targets });
  return data.data;
};

// ==========================================
// CATEGORY TARGETS API
// ==========================================

/**
 * Get category targets for a month
 */
export const fetchCategoryTargets = async (year, month) => {
  const { data } = await api.get(`/targets/categories/${year}/${month}`);
  return data.data;
};

/**
 * Save category target
 */
export const saveCategoryTarget = async (targetData) => {
  const { data } = await api.post('/targets/category', targetData);
  return data.data;
};

// ==========================================
// FALLBACK CALCULATION HELPERS
// ==========================================

/**
 * Calculate fallback target based on previous month's actuals
 * Returns target = previous_month * 1.10 (10% growth)
 */
const calculateFallbackTarget = async (year, month, knownPreviousRevenue = null) => {
  // Calculate previous month
  let prevYear = year;
  let prevMonth = month - 1;
  
  if (prevMonth === 0) {
    prevMonth = 12;
    prevYear = year - 1;
  }
  
  let previousRevenue = knownPreviousRevenue;
  let previousMargin = 35;
  
  // Try to get actual previous month data
  if (!previousRevenue) {
    try {
      // Get previous month's actual revenue from reports
      const { data: prevTarget } = await api.get(`/targets/business/${prevYear}/${prevMonth}`);
      previousRevenue = prevTarget.target_revenue;
      previousMargin = prevTarget.target_gross_margin;
    } catch (e) {
      // If no previous target, try to get actual revenue
      try {
        const firstDay = `${prevYear}-${String(prevMonth).padStart(2, '0')}-01`;
        const lastDay = new Date(prevYear, prevMonth, 0).toISOString().split('T')[0];
        const { data: metrics } = await api.get('/reports/dashboard', {
          params: { startDate: firstDay, endDate: lastDay }
        });
        previousRevenue = metrics.totalRevenue || 1000000;
        previousMargin = metrics.grossMargin || 35;
      } catch (e2) {
        // Ultimate fallback
        previousRevenue = 1000000;
        previousMargin = 35;
      }
    }
  }
  
  // Apply 10% growth
  const targetRevenue = Math.round(previousRevenue * 1.10);
  
  return {
    year,
    month,
    target_revenue: targetRevenue,
    target_gross_margin: previousMargin,
    target_cash_reserve_days: 30,
    max_outstanding_ratio: 20,
    default_staff_target_revenue: Math.round(targetRevenue / 20), // Rough estimate: 20 staff
    isAutoGenerated: true,
    basedOn: { year: prevYear, month: prevMonth, revenue: previousRevenue }
  };
};

// ==========================================
// DASHBOARD INTEGRATION HELPERS
// ==========================================

/**
 * Enrich dashboard metrics with targets
 * This is the main function called by the dashboard
 */
export const getDashboardTargets = async (year, month, currentMetrics = {}) => {
  // Get business target (with auto-fallback)
  const businessTarget = await getOrCreateBusinessTarget(
    year, 
    month, 
    currentMetrics.previousRevenue
  );
  
  // Get staff targets
  let staffTargets = [];
  try {
    staffTargets = await fetchAllUserTargets(year, month);
  } catch (e) {
    // Use defaults
  }
  
  return {
    // Main targets
    targetRevenue: businessTarget.target_revenue,
    targetGrossMargin: businessTarget.target_gross_margin,
    targetCashReserveDays: businessTarget.target_cash_reserve_days,
    targetOutstandingRatio: businessTarget.max_outstanding_ratio,
    
    // Staff defaults
    defaultStaffTargetRevenue: businessTarget.default_staff_target_revenue,
    
    // Staff-specific targets (map by user_id)
    staffTargetsMap: staffTargets.reduce((acc, t) => {
      acc[t.user_id] = t;
      return acc;
    }, {}),
    
    // Metadata
    isAutoGenerated: businessTarget.isAutoGenerated,
    isUnsaved: businessTarget.isUnsaved,
    
    // Calculated gaps
    revenueGap: Math.max(0, businessTarget.target_revenue - (currentMetrics.totalRevenue || 0)),
    marginGap: (businessTarget.target_gross_margin || 35) - (currentMetrics.grossMargin || 0),
  };
};

export default {
  fetchBusinessTarget,
  getOrCreateBusinessTarget,
  saveBusinessTarget,
  updateBusinessTarget,
  fetchYearlyTargets,
  bulkUpdateTargets,
  fetchUserTarget,
  saveUserTarget,
  fetchAllUserTargets,
  bulkUpdateUserTargets,
  fetchCategoryTargets,
  saveCategoryTarget,
  getDashboardTargets,
};
