-- Migration: Create event-posters storage bucket
-- Date: 2026-03-30
--
-- !! STORAGE SETUP MUST BE DONE MANUALLY !!
-- The storage bucket and its RLS policies cannot be created via the migration
-- runner because storage.objects is owned by supabase_storage_admin.
--
-- Run the contents of:
--   api/src/database/storage_setup.sql
-- directly in the Supabase SQL editor (Dashboard → SQL Editor).
--
-- This file is intentionally empty so the migration runner marks it as applied.
